import './body/$_get';
import './body/api-search';
import './body/auto-anchor';
import './body/data-click-is-active';
import './body/data-click-toggle-class';
import './body/data-anchors-menu';
import './body/data-headings-add-anchor';
import './body/data-open-menu';
import './body/example-tabs';
import './body/easy-slides';
// import './body/modernizr.objectfit';
import './body/doc-types';
import './body/onscreen';
import './body/source-button';
import './body/table-collapse';
